### ISSUE TITLE
Visible clipping artifacts in highlights with Malvar (2004) and Menon (2007).

### ISSUE THREAD

**Issue by jiawen** [colour-science/colour-demosaicing#7] opened 2018-01-24 19:18 UTC
My apologies ahead of time for not posting images as I am uncertain whether I have the appropriate rights.

I just tried demosaicing_CFA_Bayer_Malvar2004() and demosaicing_CFA_Bayer_Menon2007() on the standard MATLAB test image "mandi.tif" (see https://www.mathworks.com/help/images/ref/demosaic.html).

With the Malvar method, I see distinctive speckles of pure red and blue in the output near highlights. Besides that, the results are basically identical to that of MATLAB.

With the Menon method, there are pure red, green, and blue everywhere.

I suspect these are some bugs in the way overflow and underflow are handled.

**Comment by KelSolaar** [comment] 2018-01-25 06:26
Hi @jiawen,

I could not reproduce the issue:

```python
import colour
import colour_demosaicing

RGB = colour_demosaicing.demosaicing_CFA_Bayer_Menon2007(
    colour.read_image('mandi.tif'), 'BGGR')

colour.write_image(RGB, 'mandi_Menon2007.jpg')
```

**Malvar (2004)**
![image](https://user-images.githubusercontent.com/99779/35373850-4aa88cd0-0205-11e8-9f7e-4534cd665dbd.png)

**Menon (2007)**
![image](https://user-images.githubusercontent.com/99779/35373878-6fd9dfb8-0205-11e8-8c3c-4b04aa852838.png)

How are you invoking the function(s)?

**Comment by jiawen** [comment] 2018-02-01 02:16
My apologies for the delay as I got distracted by other stuff at work. Maybe it's because I'm reading the input using skimage.io.imread() instead of colour.read_image()?

Anyway, here's the [IPython notebook I was using](https://drive.google.com/open?id=1rNmftEwysA-83Upzn6Wqk8ASBS0RmP50), and this is the [output from Malvar](https://drive.google.com/open?id=1w5t-WFBHmhNhmTW_xSy-UhTOFMNp-zj9).

**Comment by almost-everywhere** [comment] 2018-02-01 02:23
I'm using colour-demosaicing 0.1.2 installed from pip on Python 3.6.

I'm not using colour.read_image() mainly because I have no idea how to easily install OpenImageIO into Anaconda without installing it system-wide.

**Comment by jiawen** [comment] 2018-02-01 02:33
I'm using colour-demosaicing 0.1.2 installed from pip on Python 3.6.

I'm not using colour.read_image() mainly because I have no idea how to easily install OpenImageIO into Anaconda without installing it system-wide.

**Comment by KelSolaar** [comment] 2018-02-01 03:29
@jiawen : I will try to look at that over the weekend, by the mean time can you try converting the array you get from `skimage.io.imread` to float and maybe divide it by 255 or 65535 before passing it to `demosaicing_CFA_Bayer_Menon2007`?

Cheers,

Thomas

**Comment by KelSolaar** [comment] 2018-02-18 04:05
Hi @jiawen,

I'm closing this for now, feel free to continue the discussion though.

Cheers,

Thomas

**Closed by KelSolaar** 2018-02-18 04:05 UTC
